Algoritmo "soma"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/06/2022
Var

   valor1, valor2, Total : inteiro


Inicio

 escreva("Qual o primeiro valor? ")
 leia(valor1)
 escreva("Qual o segundo valor? ")
 leia(valor2)
 
    Total <- valor1 + valor2
    
    escreval("Valor total: ", valor1 + valor2)


Fimalgoritmo